dist: xenial
language: python
python:
- '3.7'
install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
- conda activate test-environment
- conda install pytest
- pip install .
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: KhFI76dfaf4BR41dtr9hwk3PsdkSVRhFFhgAGFpmoGFL47vRLBq7GTeNW8y15dcbeWLbPiIfzr/GVaScQWQ+8IebPtkP7qw4+VXNAxM9CPdN3H1W30x4E1pu+/QMc+bxplASxxJHhF1X/hXfBQQFNyEHpBSFWoJFcC01W4bnOyHT33hdYzFY6KrVMMZzFlYqtMlh1tdjIYVN6LCmNdAzAjBmx31wv/75odyGBNB/wxKgGZvTCAPPSOI9AVg1c2EOBUORLE+YuWJulPHxKfsW6VWaP5WyAbhYg+1AqbSf7yzbatNF2F2aCJh4Hr0bmvCPYJA5Bkzyodvrh/dTDvb0+H42XXyvgdklYw2Zj2vP4Tkwu16UZ/yi6vi+b+BfvwLji3Q2LyNKFbV3hmF/7SChrHzRNmDMpEsQtGDa9NlTwr/FXL6/NQxnKGrLTByeLWyIOw2aZ+TwIhCQOkbxnUrD7/oAPGpksQHKWzg/GbrFCrHsUbpG+D9ndIGDkmHTSgPYgACHxCwuXSfB/cqCXFErzxK1bZ1BP9SzNpr/MBVwEIakNFOouQIfuaOqfUZwIwFahLnKHyOImplQOBJPYEjNF6A4WedvPuOb2gV9v5NptKjinj7gS/AvvcQscftCETJsY8cCkXB0a/BANeMtXjOXpY1jCU1draBRkp6CHl+CWlg=
  on:
    tags: true
